### ISSUE TITLE
If btrdb crashes while plotter is active, mr-plotter spins and does not recover

### ISSUE THREAD

**Issue by gtfierro** [BTrDB/mr-plotter#1]
It keeps outputting the errors on lines [246](https://github.com/SoftwareDefinedBuildings/mr-plotter/blob/master/data.go#L246) and [462](https://github.com/SoftwareDefinedBuildings/mr-plotter/blob/master/data.go#L462). Even after btrdb comes back up, the plotter doesn't seem to try to reconnect or at least abandon the old transaction.

**Comment by samkumar** [comment]
Fixed in commit 48ca94b1f46947f03944c9afee44f9e1d6cbd88b. Now Mr. Plotter exits cleanly if the connection to BTrDB is lost. Thanks for finding this.
