### ISSUE TITLE
Permalink disappears when plot refreshes

### ISSUE THREAD

**Issue by gtfierro** [BTrDB/mr-plotter#2]
If you click 'generate permalink', the link disappears when the plot fetches the latest batch of data from the backend.

**Comment by immesys** [comment]
That is intended behavior, but perhaps annoying. Sam can you keep the behavior of the permalink disappearing when you scroll / zoom, but don't make it disappear if it has just been an automatic refresh without any manipulation of the plot?

**Comment by samkumar** [comment]
Thanks for finding this. Fixed in 4e33605cd0069982cad5ebf540929f78d8300a49.
