### ISSUE TITLE
Some problems getting the plotter to play together with giles2 and btrdb

### ISSUE THREAD

**Issue by jf87** [BTrDB/mr-plotter#4]
Hi Sam,

I've just set up giles2 and btrdb.
Even there is data in my timeseries, the plotter does not seem to be able to access it (see screenshot).

<img width="620" alt="screenshot 2016-04-20 19 47 57" src="https://cloud.githubusercontent.com/assets/2108882/14684549/ce16ef0c-0730-11e6-9115-10a5fd1fbcc4.png">

The plotter throws the following errors:

`
Number of goroutines: 14
2016/04/20 10:45:53 http: panic serving 192.168.116.1:62749: runtime error: invalid memory address or nil pointer dereference
goroutine 198 [running]:
net/http.(*conn).serve.func1(0x96a3cd40)
    /usr/lib/go/src/net/http/server.go:1389 +0xa2
panic(0x8435d40, 0x968c0030)
    /usr/lib/go/src/runtime/panic.go:426 +0x3fd
sync/atomic.AddUint64(0x968ac84c, 0x1, 0x0, 0x0, 0x0)
    /usr/lib/go/src/sync/atomic/asm_386.s:112 +0xc
main.(*DataRequester).MakeBracketRequest(0x968ac820, 0x96b6c540, 0x1, 0x1, 0x85f1bb38, 0x968c06c8)
    /home/jofu/go/src/github.com/SoftwareDefinedBuildings/mr-plotter/data.go:305 +0xe8
main.bracketHandler(0x85f1bac8, 0x96a8d300, 0x9695c1c0)
    /home/jofu/go/src/github.com/SoftwareDefinedBuildings/mr-plotter/serveplotter.go:581 +0x673
net/http.HandlerFunc.ServeHTTP(0x854bc30, 0x85f1bac8, 0x96a8d300, 0x9695c1c0)
    /usr/lib/go/src/net/http/server.go:1618 +0x34
net/http.(*ServeMux).ServeHTTP(0x968a6fe0, 0x85f1bac8, 0x96a8d300, 0x9695c1c0)
    /usr/lib/go/src/net/http/server.go:1910 +0x133
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x85f1a1d8, 0x968c00d8, 0x85f1b818, 0x968a6fe0, 0x85f1b9d0, 0x96a4ef60, 0x9695c1c0)
    /home/jofu/go/src/github.com/gorilla/handlers/handlers.go:77 +0xed
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0x96944a90, 0x85f1b9d0, 0x96a4ef60, 0x9695c1c0)
    <autogenerated>:15 +0x9b
github.com/gorilla/handlers.CompressHandlerLevel.func1(0x85f1b9d0, 0x96a4ef60, 0x9695c1c0)
    /home/jofu/go/src/github.com/gorilla/handlers/compress.go:143 +0x4d8
net/http.HandlerFunc.ServeHTTP(0x96944aa0, 0x85f1b908, 0x9690a780, 0x9695c1c0)
    /usr/lib/go/src/net/http/server.go:1618 +0x34
net/http.serverHandler.ServeHTTP(0x968ac870, 0x85f1b908, 0x9690a780, 0x9695c1c0)
    /usr/lib/go/src/net/http/server.go:2081 +0x156
net/http.(*conn).serve(0x96a3cd40)
    /usr/lib/go/src/net/http/server.go:1472 +0xed8
created by net/http.(*Server).Serve
    /usr/lib/go/src/net/http/server.go:2137 +0x394
`

My config file is below.
Maybe you can help me, thanks :-)

`
http_port=8888
https_port=4433
use_http=true
use_https=false
https_redirect=false
plotter_dir=/home/jofu/go/src/github.com/SoftwareDefinedBuildings/mr-plotter/assets
cert_file=cert.pem
key_file=key.nocrypt.pem
db_addr=localhost:4410
num_data_conn=3
num_bracket_conn=2
max_data_requests=8
max_bracket_requests=8
metadata_server=http://localhost:8079/api/query
mongo_server=localhost:27017
csv_url=http://localhost:9000/directcsv

session_expiry_seconds=604800 # 1 week
session_purge_interval_seconds=14400 # 6 hours
csv_max_points_per_stream=100000
outstanding_request_log_interval=30
num_goroutines_log_interval=10
db_data_timeout_seconds=10
db_bracket_timeout_seconds=10
`

**Comment by samkumar** [comment]
Hi Jonathan,

Thanks for finding this. I suspect the issue is one of alignment: the code is trying to atomically change "dr.totalWaiting", which for some reason isn't properly aligned.

Can you please tell me what platform (Operating System and Architecture) you're using to run the plotter?

**Comment by samkumar** [comment]
I got a chance to look into this some more. It definitely looks like a padding issue that affects 32-bit systems (see golang/go#599).

I've pushed an update that should fix this issue, but since I don't have a 32-bit system it is difficult for me to test it. If you still run into this issue, feel free to reopen this issue.

**Comment by jf87** [comment]
Hey Sam,

you are right with the 32bit system. I did dry-run all the setup on a VM on my local machine, which is still 32bit. With your fix it works perfectly now. Thanks :-)

**Comment by immesys** [comment]
Please note that BTrDB really requires a 64-bit machine, it will do Bad Things on 32 bit

**Comment by jf87** [comment]
Ok. I just installed it for testing purpose on that VM, the actual server is 64-bit. Up to now it seems to behave though ;-)
