### ISSUE TITLE
Leaf removals

### ISSUE THREAD

**Issue by TechauraIO** [BTrDB/mr-plotter#9]
We could use some documentation regarding cleaning up the tree when either mistakes are made or we have the need to declutter the interface.  The total kludge is doing it with ACLs which is a very good solution to the problem.

**Comment by immesys** [comment]
To delete a stream, along with all its historical data, you would use the [Obliterate API function](https://github.com/go-btrdb/btrdb/blob/v4/grpcinterface/btrdb.proto#L21) but we do not support it yet. The work is partially done but we will likely only get it out in a few weeks

**Comment by TechauraIO** [comment]
Per my #slack message, we totally want to separate the idea of data curation from the GUI representations for a number of different reasons.   We really don't want to blow out the data, in fact that is likely the last thing we'd want to do.   Also, understand this is a lot of the tooling and refinement we want to bring to the interfaces but wanted to get clarification on if there was anything available now fix the trees.   Metadata changes in console do nothing if you change or delete entire leafs.

**Comment by immesys** [comment]
@pingthings, we now support obliterating streams (or have for a while). Until we actually create a layer of indirection between the UI and the streams, I am going to mark this as solved.
